cms/urls.py
from django.urls import path
from cms import views


app_name = 'cms'
urlpatterns = [

    path('recoman_top/', views.recoman_top, name='recoman_top'),   # top
    path('recoman_top/recommend', views.recommend, name='recoman_recommend'),  # recommend
    path('recoman_top/history', views.recoman_history, name='recoman_history'),  # history
]

recoman/urls.py
from django.contrib import admin
from django.urls import path, include   # ←, includeを追加

urlpatterns = [
    path('cms/', include('cms.urls')),   # ←ここを追加
    path('admin/', admin.site.urls),
]

cms/models.py
from django.db import models


class Book(models.Model):
    """書籍"""
    series = models.CharField('シリーズ名', max_length=255)
    # publisher = models.CharField('出版社', max_length=255, blank=True)
    #  page = models.IntegerField('ページ数', blank=True, default=0)

    def __str__(self):
        return self.series

cms/forms.py
from django import forms
from django.core.validators import MaxValueValidator, MinValueValidator


class select_manga(forms.Form):
    username = forms.CharField(max_length=100,
                               label='ユーザー名',
                               # widget=forms.HiddenInput(),
                               # initial='skaidmd'
                               # widget=forms.TextInput(attrs={'placeholder': 'ユーザー名'}))
                               )

    manga1 = forms.CharField(max_length=100,
                             label='漫画１',
                             widget=forms.TextInput(attrs={'placeholder': 'シリーズ名'}))
    evaluat1 = forms.IntegerField(
        # evaluat1=forms.IntegerField(validators=[MinValueValidator(1),MaxValueValidator(5)],
        label='漫画評価１',
        widget=forms.TextInput(attrs={'placeholder': '1~5'}))

    manga2 = forms.CharField(max_length=100,
                             label='漫画２',
                             widget=forms.TextInput(attrs={'placeholder': 'シリーズ名'}))
    evaluat2 = forms.IntegerField(
        # evaluat2=forms.IntegerField(validators=[MinValueValidator(1),MaxValueValidator(5)],
        label='漫画評価２',
        widget=forms.TextInput(attrs={'placeholder': '1~5'}))

    manga3 = forms.CharField(max_length=100,
                             label='漫画３',
                             widget=forms.TextInput(attrs={'placeholder': 'シリーズ名'}))
    evaluat3 = forms.IntegerField(
        # evaluat3=forms.IntegerField(validators=[MinValueValidator(1),MaxValueValidator(5)],
        label='漫画評価３',
        widget=forms.TextInput(attrs={'placeholder': '1~5'}))

    manga4 = forms.CharField(max_length=100,
                             label='漫画４',
                             widget=forms.TextInput(attrs={'placeholder': 'シリーズ名'}))
    evaluat4 = forms.IntegerField(
        # evaluat4=forms.IntegerField(validators=[MinValueValidator(1),MaxValueValidator(5)],
        label='漫画評価４',
        widget=forms.TextInput(attrs={'placeholder': '1~5'}))

    manga5 = forms.CharField(max_length=100,
                             label='漫画５',
                             widget=forms.TextInput(attrs={'placeholder': 'シリーズ名'}))
    evaluat5 = forms.IntegerField(
        # evaluat5=forms.IntegerField(validators=[MinValueValidator(1),MaxValueValidator(5)],
        label='漫画評価５',
        widget=forms.TextInput(attrs={'placeholder': '1~5'}))

    def clean_evaluat(self):
        evaluat = self.cleaned_data['evaluat1']

        print(evaluat)
        if evaluat < 1 or evaluat > 5:
            raise forms.ValidationError('範囲外です。')

        return evaluat

cms/views.py
from django.shortcuts import render
from .forms import select_manga
import numpy as np

import sys
sys.path.append("/Users/skai/PycharmProjects/recoman/cms")


def recoman_top(request):
    """recoman_top"""
    username = 'testuser'

    return render(request,'cms/recoman_top.html',{'username':username})

def recommend(request):
    """recoman_recommend"""
    form = select_manga()

    # ページ到達時点でjsonデータ読み込み、データ化
    # ページ到達に関わらないアプローチに変えたい
    # boklog_content_v2.load_log('dummy')

    return render(request,
                    'cms/recoman_recommend.html',
                    {'form': form})

def recoman_history(request):
    """recoman_history"""
    return render(request,'cms/recoman_history.html')

cms/templates/cms/base.html
{% load i18n static %}
<!DOCTYPE html>{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
    <script src="{% static 'cms/js/jquery-3.3.1.min.js' %}"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'cms/css/bootstrap.min.css' %}">
    {% block extra_css %}{% endblock %}
    <title>{% block title %}My books{% endblock %}</title>
</head>
<body>
<div class="container">
    {% block content %}
        {{ content }}
    {% endblock %}
</div>
<script src="{% static 'cms/js/bootstrap.bundle.min.js' %}"></script>
{% block extra_js %}{% endblock %}
</body>
</html>

cms/templates/cms/recoman_history.html
{% extends "cms/base.html" %}

{% block title %}recoman_history{% endblock title %}

{% block content %}
    <h4 class="mt-4 border-bottom text-center">recoman_history</h4>
      <tbody>
        <tr>
         <td>
            <a href="{% url 'cms:recoman_top'  %}" class="btn btn-outline-primary btn-sm">戻る</a>
          </td>
        </tr>
      </tbody>
{% endblock content %}

cms/templates/cms/recoman_recommend.html
{% extends "cms/base.html" %}

{% block title %}recoman_recommend{% endblock title %}

{% block content %}
    <h4 class="mt-4 border-bottom text-center">recoman_recommend</h4>
    <label for="select_manga">漫画情報入力</label>
    <div>
        <form action="">
            <div>{{ form }}</div>
            <input type="button" value="送信" id="send"/>
            <p id="result"></p>
        </form>
    </div>
    <script type="text/javascript">
        //TODO:  Ajax button click
        $(function () {
            $('#send').on('click', function () {

                // 入力された名前を取得する
                var name = $('#id_username').val()
                var series = {}

                for (var i = 1; i <= 5; i++) {
                    var mangattitle = $('#id_manga' + i).val()
                    var evaluat = $('#id_evaluat' + i).val()

                    series[mangattitle] = evaluat
                }
                console.log(name, series)

                // ajaxでrecommendAPIへリクエストする
                $.ajax({
                    url: 'http://127.0.0.1:5001/cms/api/analyze',
                    type: 'POST',
                    dataType: 'json',
                    data: JSON.stringify({
                        'name': name,
                        'series': series
                    }),
                    //TODO: lodingを表示する

                    //TODO: ajaxのレスポンスをページへ表示する
                    //コールバック後の処理
                    success: function (json) {
                        $('#result').append(JSON.stringify(json));
                    },
                    error: function () {
                        $('#result').append('error');
                    }

                })
                // Ajaxリクエストが成功した時発動
                    .done((json) => {
                        $('#result').append(json);
                        console.log(json);
                    });
            });
        });
    </script>
{% endblock content %}

cms/templates/cms/recoman_search.html
{% extends "cms/base.html" %}

{% block title %}recoman_search{% endblock title %}

{% block content %}
    <h4 class="mt-4 border-bottom text-center">recoman_search</h4>
    <label for="select_manga">漫画の設定</label>
      <body>
{#        <tr>#}
{#            <form>#}
{#                <div class="form-select_manga">#}
{#                    <input type="text" class="form-control" id="Sereis1" placeholder="好きな漫画１">#}
{#                    <input type="text" class="form-control" id="Sereis2" placeholder="好きな漫画２">#}
{#                    <input type="text" class="form-control" id="Sereis3" placeholder="好きな漫画３">#}
{#                    <input type="text" class="form-control" id="Sereis4" placeholder="好きな漫画４">#}
{#                    <input type="text" class="form-control" id="Sereis5" placeholder="好きな漫画５">#}
{#                </div>#}
{#            </form>#}
{#            <td>#}
{#                <form action="" method="post">#}
{#                    <input type="submit" value="レコメンドを確認">#}
{#                </form>#}
{#                <a href="{% url 'cms:recoman_top'  %}" class="btn btn-outline-primary btn-sm">戻る</a>#}
{#            </td>#}
{#        </tr>#}
        <form action="{% url 'cms:recoman_searchresult'  %}" method="POST">
            {% csrf_token %}

            <div>{{ form }}</div>
            <input type="submit" value="送信"/>
        </form>
      </body>
{% endblock content %}

cms/templates/cms/recoman_top.html
{% extends "cms/base.html" %}

{% block title %}recoman_top{% endblock title %}

{% block content %}
    <h4 class="mt-4 border-bottom text-center">recoman_top</h4>
{#    <a href="{% url 'cms:book_add' %}" class="btn btn-primary btn-sm my-3">追加</a>#}
{#    <table class="table table-striped table-bordered">#}
{#      <thead>#}
{#        <tr>#}
{#          <th scope="col">ID</th>#}
{#          <th scope="col">書籍名</th>#}
{#          <th scope="col">出版社</th>#}
{#          <th scope="col">ページ数</th>#}
{#          <th scope="col">操作</th>#}
{#        </tr>#}
{#      </thead>#}
      <tbody>
{#        {% for book in books %}#}
        <tr>
{#          <th scope="row">{{ book.id }}</th>#}
{#          <td>{{ book.name }}</td>#}
{#          <td>{{ book.publisher }}</td>#}
{#          <td>{{ book.page }}</td>#}
          <td>
{#            <a class="text-lg-left">ユーザー名:{{username}}</a>#}
            <a href="{% url 'cms:recoman_recommend'  %}" class="btn btn-outline-primary btn-lg btn-block">おすすめ漫画を探す</a>
            <a href="{% url 'cms:recoman_history' %}" class="btn btn-outline-success btn-lg btn-block">過去のレコメンド結果を見る</a>
          </td>
        </tr>
{#        {% endfor %}#}
      </tbody>
{#    </table>#}
{% endblock content %}